spring.application.name=CarrerSathi
server.port=1111
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://dpg-d6ugv2qa214c73d4bddg-a.singapore-postgres.render.com:5432/carrersathi?sslmode=require
spring.datasource.username=carrersathi_user
spring.datasource.password=UI43QWH8uMqc9NQlMRQZAdWKH2INEKY1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jdbc.template.fetch-size=100